### PR TITLE
Add deployment

### PR DESCRIPTION
**Pull request by karhong-sam**
Deployment files include:

- explore.py: To visualize the charts
- predict.py: To perform ML prediction in form
- app.py: To import both explore.py and predict.py on same file to execute `streamlit run app.py` command

Minor Adjustment include:
- rerun superstore_analysis.ipynb file to get some outputs
- added few datasets for deployment usage

### CODE REVIEW

**Comment by jhwong97** [comment]
image

May I know what's the difference between sales and quantity?

Besides, it seems like there is a conflict for superstore_analysis.ipynb.

**Review by jhwong97 — COMMENTED** [review]
image

What's the difference between sales and quantity? 
It seems like repetitive.

Other than that, there's no further comments everything looks good

**Comment by karhong-sam** [comment]
> image
> 
> What's the difference between sales and quantity? It seems like repetitive.
> 
> Other than that, there's no further comments everything looks good

The 'Quantity' is retrived from the latest saved date, df_transform.csv. If want to remove it, we might need to hard delete it from the xgboost model too which mean to retrain the xgboost clasifier. Else, there will be error popups where the final output layer columns was mismatched with the data and the model trained.

**Comment by jhwong97** [comment]
> > image
> > What's the difference between sales and quantity? It seems like repetitive.
> > Other than that, there's no further comments everything looks good
> 
> The 'Quantity' is retrived from the latest saved date, df_transform.csv. If want to remove it, we might need to hard delete it from the xgboost model too which mean to retrain the xgboost clasifier. Else, there will be error popups where the final output layer columns was mismatched with the data and the model trained.

If like this, I think we can just merge all this files to main.
Any issues arise, we only settle during our presentation

**Review by jhwong97 — APPROVED** [review]

**Pull request merged**
